version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  image:
    docker:
      - image: 'cypress/base:14.19.0'
workflows:
  test:
    jobs:
      - cypress/run:
          executor: image
          yarn: true
          command: yarn test:e2e:ci
