version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  test:
    jobs:
      - cypress/run:
          matrix:
            parameters:
              executor:
                - cypress/base:14.17.0
          yarn: true
          command: yarn test:e2e --headless
