version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  test:
    jobs:
      - cypress/run:
          docker:
            - image: 'cypress/base:14'
          yarn: true
          command: yarn test:e2e --headless
